<?php
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/db.php';
setCors();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') err('Solo POST', 405);

$b = body();
if (($b['admin_password'] ?? '') !== ADMIN_PASSWORD) err('Contraseña incorrecta', 403);

$db = getDB();
$db->exec('CREATE TABLE IF NOT EXISTS custom_vehicles (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  make        VARCHAR(100) NOT NULL,
  model       VARCHAR(100) NOT NULL,
  version     VARCHAR(200) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_vehicle (make, model, version)
)');

$vehicles = [
  ['BYD', 'Atto 2', 'DM-i Active'],
  ['Leapmotor', 'B10', 'Life REEV Hybrid'],
  ['BYD', 'Atto 2', 'DM-i Boost'],
  ['Leapmotor', 'B10', 'Design REEV Hybrid'],
  ['BYD', 'Seal 6', 'DM-i Boost'],
  ['Peugeot', '308 5p', 'Style Plug-In Hybrid 195 e-DCS7'],
  ['BYD', 'Seal 6', 'DM-i Touring Boost'],
  ['Geely', 'Starray', 'EM-i PRO'],
  ['Leapmotor', 'C10', 'Style REEV'],
  ['Peugeot', '308 SW', 'Style Plug-In Hybrid 195 e-DCS7'],
  ['Toyota', 'C-HR', 'Plug-in Hybrid 220 Business'],
  ['Peugeot', '308 5p', 'Allure Plug-In Hybrid 195 e-DCS7'],
  ['BYD', 'Seal 6', 'DM-i Comfort Lite'],
  ['Opel', 'Astra', 'GS Plug-in-Hybrid 195 CV'],
  ['Toyota', 'C-HR', 'Plug-in Hybrid 220 Advance'],
  ['Leapmotor', 'C10', 'Design REEV'],
  ['BYD', 'Seal U', 'DM-i Boost'],
  ['Peugeot', '308 SW', 'Allure Plug-In Hybrid 195 e-DCS7'],
  ['DFSK', 'E5', 'Intelligent'],
  ['BYD', 'Seal 6', 'DM-i Comfort'],
  ['Ebro', 's700', 'PHEV Premium'],
  ['Geely', 'Starray', 'EM-i PRO+'],
  ['MG', 'HS', 'PHEV Comfort'],
  ['Opel', 'Astra Sports Tourer', 'GS Plug-in-Hybrid 195 CV'],
  ['BYD', 'Seal 6', 'DM-i Touring Comfort Lite'],
  ['BYD', 'Seal 6', 'DM-i Touring Comfort'],
  ['Peugeot', '308 5p', 'GT Plug-In Hybrid 195 e-DCS7'],
  ['Ebro', 's700', 'PHEV Luxury'],
  ['Toyota', 'C-HR', 'Plug-in Hybrid 220 Spirit'],
  ['Ford', 'Tourneo Connect', 'Trend 1.5 EcoBoost PHEV 150 CV'],
  ['Bestune', 'Joyee 07', 'PHEV'],
  ['Geely', 'Starray', 'EM-i MAX+'],
  ['Ford', 'Kuga', 'Titanium 2.5 PHEV 243 CV'],
  ['Jeep', 'Compass', '4xe PHEV 190 CV Altitude'],
  ['Peugeot', '308 SW', 'GT Plug-In Hybrid 195 e-DCS7'],
  ['Kia', 'XCeed', 'eDrive 1.6 PHEV 141 CV'],
  ['Toyota', 'C-HR', 'Plug-in Hybrid 220 GR Sport'],
  ['Volkswagen', 'Golf', 'Match 1.5 eHybrid 204 CV DSG'],
  ['BYD', 'Seal U', 'DM-i Comfort'],
  ['Skoda', 'Kodiaq', 'Selection 1.5 TSI iV PHEV 204 CV DSG'],
  ['Jaecoo', '7', 'SHS PHEV Select'],
  ['Ford', 'Grand Tourneo Connect', 'Trend 1.5 EcoBoost PHEV 150 CV'],
  ['MG', 'HS', 'PHEV Luxury'],
  ['Ford', 'Grand Tourneo Connect', 'Trend PHEV 150 CV 7 plazas'],
  ['Peugeot', '308 5p', 'GT Exclusive Plug-In Hybrid 195 e-DCS7'],
  ['Citroën', 'C5 Aircross', 'Plus Plug-in Hybrid 225 CV'],
  ['Ford', 'Kuga', 'ST-Line 2.5 PHEV 243 CV'],
  ['Ford', 'Tourneo Connect', 'Titanium 1.5 EcoBoost PHEV 150 CV'],
  ['BYD', 'Seal U', 'DM-i Design AWD'],
  ['Peugeot', '308 SW', 'GT Exclusive Plug-In Hybrid 195 e-DCS7'],
  ['Kia', 'XCeed', 'eTech 1.6 PHEV 141 CV'],
  ['Opel', 'Grandland', 'Edition Plug-in Hybrid 195 CV'],
  ['Jeep', 'Compass', '4xe PHEV 240 CV North Star'],
  ['Ebro', 's800', 'PHEV Premium'],
  ['SEAT', 'León', '1.5 eHybrid 204 CV DSG Style'],
  ['Citroën', 'C5 Aircross', 'Business Plug-in Hybrid 225 CV'],
  ['Jaecoo', '7', 'SHS PHEV Exclusive'],
  ['Omoda', '7', 'SHS PHEV Pure 1.5 TGDI 279 CV'],
  ['Lynk & Co', '01', 'Core'],
  ['Volkswagen', 'Golf', 'Style 1.5 eHybrid 204 CV DSG'],
  ['Volkswagen', 'Caddy', 'Origin 1.5 TSI Hybrid 150 CV DSG'],
  ['Peugeot', '3008', 'Allure Plug-in Hybrid 195 e-DCS7'],
  ['Ford', 'Grand Tourneo Connect', 'Titanium PHEV 150 CV'],
  ['Toyota', 'C-HR', 'Plug-in Hybrid 220 GR Sport Plus'],
  ['Peugeot', '408', 'Allure Plug-In Hybrid 240 e-DCS7'],
  ['Jeep', 'Compass', '4xe PHEV 240 CV Summit'],
  ['Kia', 'Niro', '1.6 GDi PHEV 171 CV Concept'],
  ['Ford', 'Tourneo Connect', 'Active 1.5 EcoBoost PHEV 150 CV'],
  ['SEAT', 'León', '1.5 eHybrid 204 CV DSG FR XM'],
  ['Kia', 'XCeed', 'eMotion 1.6 PHEV 141 CV'],
  ['SEAT', 'León Sportstourer', '1.5 eHybrid 204 CV DSG Style'],
  ['CUPRA', 'León 5p', 'eHybrid 204 CV DSG'],
  ['MG', 'MGS9', 'PHEV Comfort'],
  ['Ford', 'Kuga', 'ST-Line X 2.5 PHEV 243 CV'],
  ['Peugeot', '3008', 'Allure Exclusive Plug-in Hybrid 195 e-DCS7'],
  ['Citroën', 'C5 Aircross', 'Max Plug-in Hybrid 225 CV'],
  ['Ford', 'Kuga', 'Active X 2.5 PHEV 243 CV'],
  ['Ford', 'Grand Tourneo Connect', 'Active PHEV 150 CV'],
  ['Volkswagen', 'Golf', 'GTE 1.5 TSI 272 CV DSG'],
  ['Skoda', 'Kodiaq', 'Sportline 1.5 TSI iV PHEV 204 CV DSG'],
  ['CUPRA', 'León 5p', 'eHybrid 204 CV DSG Beyond'],
  ['DS', 'Nº4', 'Plug-in Hybrid 240 CV Pallas'],
  ['CUPRA', 'León Sportstourer', 'eHybrid 204 CV DSG'],
  ['Peugeot', '5008', 'Allure Plug-In Hybrid 195 e-DCS7'],
  ['CUPRA', 'Formentor', '1.5 eHybrid 204 CV DSG'],
  ['Volkswagen', 'Caddy Maxi', 'Origin 1.5 TSI Hybrid 150 CV DSG 7 plazas'],
  ['SEAT', 'León Sportstourer', '1.5 eHybrid 204 CV DSG FR XM'],
  ['Hyundai', 'Tucson', 'Klass 1.6 T-GDi PHEV 288 CV'],
  ['Opel', 'Grandland', 'GS Plug-in Hybrid 195 CV'],
  ['Omoda', '7', 'SHS PHEV Premium 1.5 TGDI 279 CV'],
  ['CUPRA', 'León Sportstourer', 'eHybrid 204 CV DSG Beyond'],
  ['Kia', 'Niro', '1.6 GDi PHEV 171 CV Drive'],
  ['Volkswagen', 'Caddy', 'Outdoor 1.5 TSI Hybrid 150 CV DSG'],
  ['CUPRA', 'Formentor', '1.5 eHybrid 204 CV DSG Beyond'],
  ['Peugeot', '408', 'GT Plug-In Hybrid 240 e-DCS7'],
  ['Volkswagen', 'Tiguan', 'Más 1.5 TSI eHybrid 204 CV'],
  ['DS', 'Nº4', 'Plug-in Hybrid 240 CV Performance Line'],
  ['Lynk & Co', '01', 'More'],
  ['MG', 'MGS9', 'PHEV Premium'],
  ['CUPRA', 'Terramar', '1.5 eHybrid 204 CV DSG'],
  ['Ford', 'Kuga', 'BlueCruise Edition 2.5 PHEV 243 CV'],
  ['Hyundai', 'Tucson', 'Black Line 1.6 T-GDi PHEV 288 CV'],
  ['Peugeot', '3008', 'GT Plug-in Hybrid 195 e-DCS7'],
  ['DS', 'Nº4', 'Plug-in Hybrid 240 CV Jules Verne'],
  ['Ford', 'Ranger', 'XLT Doble Cabina 2.3 PHEV 280 CV'],
  ['Alfa Romeo', 'Tonale', '1.3 Plug-In Hybrid Q4 270 CV'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 Advance'],
  ['Audi', 'A3 Sportback', 'Advanced TFSI e 204 CV'],
  ['DS', 'Nº4', 'Plug-in Hybrid 240 CV Étoile'],
  ['CUPRA', 'Terramar', '1.5 eHybrid 204 CV DSG Beyond'],
  ['Ebro', 's800', 'PHEV Luxury'],
  ['Kia', 'Niro', '1.6 GDi PHEV 171 CV Emotion'],
  ['Peugeot', '408', 'GT Exclusive Plug-In Hybrid 240 e-DCS7'],
  ['CUPRA', 'León 5p', 'VZ eHybrid 272 CV DSG'],
  ['Alfa Romeo', 'Tonale', 'Sprint 1.3 Plug-In Hybrid Q4 270 CV'],
  ['Volkswagen', 'Tayron', 'Más 1.5 eHybrid 204 CV DSG'],
  ['CUPRA', 'León Sportstourer', 'VZ eHybrid 272 CV DSG'],
  ['Peugeot', '5008', 'GT Plug-In Hybrid 195 e-DCS7'],
  ['Mitsubishi', 'Outlander', 'PHEV Motion 4WD'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 Advance AWD'],
  ['Peugeot', '3008', 'GT Exclusive Plug-in Hybrid 195 e-DCS7'],
  ['Renault', 'Rafale', 'esprit Alpine hyper hybrid E-Tech 4x4 300 CV'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Prime-Line'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 Spirit'],
  ['Audi', 'A3 allstreet', 'Advanced TFSI e 204 CV'],
  ['CUPRA', 'Formentor', 'VZ 1.5 eHybrid 272 CV DSG'],
  ['Audi', 'A3 Sportback', 'S line TFSI e 204 CV'],
  ['Hyundai', 'Tucson', 'Tecno 1.6 T-GDi PHEV 288 CV'],
  ['Ebro', 's900', 'PHEV 4x4 Luxury'],
  ['Mercedes-Benz', 'B 250 e', 'EQ Hybrid'],
  ['Alfa Romeo', 'Tonale', 'Ti 1.3 Plug-In Hybrid Q4 270 CV'],
  ['Hyundai', 'Tucson', 'N Line 1.6 T-GDi PHEV 288 CV'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Exclusive-Line'],
  ['Omoda', '9', 'SHS AWD 1.5 TGDI Premium'],
  ['Mercedes-Benz', 'A 250 e', 'EQ Hybrid'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 Spirit AWD'],
  ['Volkswagen', 'Passat Variant', '1.5 TSI eHybrid 204 CV'],
  ['Peugeot', '5008', 'GT Exclusive Plug-In Hybrid 195 e-DCS7'],
  ['Alfa Romeo', 'Tonale', 'Sport Speciale 1.3 Plug-In Hybrid Q4 270 CV'],
  ['Honda', 'CR-V', 'Advance Tech Plug-In Hybrid 4x2'],
  ['Audi', 'A3 Sportback', 'Genuine Edition TFSI e 204 CV'],
  ['Hyundai', 'Tucson', 'Tecno 1.6 T-GDi PHEV 288 CV 4x4'],
  ['Alfa Romeo', 'Tonale', 'Veloce 1.3 Plug-In Hybrid Q4 270 CV'],
  ['Skoda', 'Superb Combi', 'Selection 1.5 TSI iV PHEV 204 CV DSG'],
  ['Audi', 'A3 allstreet', 'Genuine TFSI e 204 CV'],
  ['Skoda', 'Superb', 'Selection 1.5 TSI iV PHEV 204 CV DSG'],
  ['Lynk & Co', '08', 'Core'],
  ['CUPRA', 'Terramar', 'VZ 1.5 eHybrid 272 CV DSG'],
  ['Hyundai', 'Tucson', 'Style 1.6 T-GDi PHEV 288 CV'],
  ['Hyundai', 'Tucson', 'N Line 1.6 T-GDi PHEV 288 CV 4x4'],
  ['Renault', 'Rafale', 'atelier Alpine hyper hybrid E-Tech 4x4 300 CV'],
  ['Volkswagen', 'Tiguan', 'R-Line 1.5 TSI eHybrid 204 CV'],
  ['CUPRA', 'León 5p', 'VZ Extreme eHybrid 272 CV DSG'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 Limited AWD'],
  ['Toyota', 'RAV4', 'Plug-in Hybrid 300 GR Sport AWD'],
  ['CUPRA', 'León Sportstourer', 'VZ Extreme eHybrid 272 CV DSG'],
  ['Skoda', 'Kodiaq', 'Plus 1.5 TSI iV PHEV 204 CV DSG'],
  ['Volkswagen', 'Caravelle', 'Batalla Corta 2.5 eHybrid 232 CV CVT'],
  ['Mitsubishi', 'Outlander', 'PHEV Kaiteki 4WD'],
  ['Santana', '400', 'PHEV 4WD 429 CV'],
  ['CUPRA', 'Formentor', 'VZ Extreme 1.5 eHybrid 272 CV DSG'],
  ['Skoda', 'Superb Combi', 'Plus 1.5 TSI iV PHEV 204 CV DSG'],
  ['Skoda', 'Superb', 'Plus 1.5 TSI iV PHEV 204 CV DSG'],
  ['Volkswagen', 'Caravelle', 'Batalla Larga 2.5 eHybrid 232 CV CVT'],
  ['BMW', '225e', 'xDrive Active Tourer'],
  ['Jaecoo', '8', 'SHS Exclusive 5 plazas'],
  ['Volkswagen', 'Passat Variant', 'Business 1.5 TSI eHybrid 272 CV'],
  ['Jaecoo', '8', 'SHS Exclusive 7 plazas'],
  ['Suzuki', 'Across', '2.5 PHEV 4x4 GLX'],
  ['Hyundai', 'Tucson', 'Style 1.6 T-GDi PHEV 288 CV 4x4'],
  ['Mercedes-Benz', 'GLA 250 e', 'EQ Hybrid'],
  ['Audi', 'Q3 Business', 'e-hybrid 272 CV S tronic'],
  ['Ford', 'Ranger', 'Wildtrak Doble Cabina 2.3 PHEV 280 CV'],
  ['Volkswagen', 'Tiguan', 'R-Line 1.5 TSI eHybrid 272 CV'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Homura'],
  ['Mitsubishi', 'Outlander', 'PHEV Kaiteki+ 4WD'],
  ['BMW', 'X1', 'xDrive25e'],
  ['Hyundai', 'Tucson', 'N Line Style 1.6 T-GDi PHEV 288 CV 4x4'],
  ['Lynk & Co', '08', 'More'],
  ['Mazda', 'CX-80', 'Exclusive-Line 2.5 E-Skyactiv PHEV 327 CV AWD'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Takumi'],
  ['Audi', 'Q3 Advanced', 'e-hybrid 272 CV S tronic'],
  ['Volkswagen', 'Multivan', 'corto 1.5 eHybrid 245 CV DSG 4Motion'],
  ['Skoda', 'Superb', 'Sportline 1.5 TSI iV PHEV 204 CV DSG'],
  ['Audi', 'Q3 Sportback Business', 'e-hybrid 272 CV S tronic'],
  ['Skoda', 'Superb Combi', 'Sportline 1.5 TSI iV PHEV 204 CV DSG'],
  ['Mitsubishi', 'Outlander', 'PHEV First Edition 4WD'],
  ['Volkswagen', 'Tayron', 'R-Line 1.5 eHybrid 272 CV DSG'],
  ['Skoda', 'Superb Combi', 'L&K 1.5 TSI iV PHEV 204 CV DSG'],
  ['Skoda', 'Superb', 'L&K 1.5 TSI iV PHEV 204 CV DSG'],
  ['Santana', '400', 'PHEV S 4WD 429 CV'],
  ['Audi', 'Q3 Sportback Advanced', 'e-hybrid 272 CV S tronic'],
  ['BMW', 'X1', 'xDrive30e'],
  ['Audi', 'Q3 Progressive', 'e-hybrid 272 CV S tronic'],
  ['Volkswagen', 'Passat Variant', 'R-Line 1.5 TSI eHybrid 272 CV'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Homura Plus'],
  ['BMW', '330e', 'Berlina'],
  ['Audi', 'Q3 S line', 'e-hybrid 272 CV S tronic'],
  ['Hyundai', 'Santa Fe', 'Maxx 1.6 T-GDI PHEV 253 CV 4x4'],
  ['Land Rover', 'Discovery Sport', 'Dynamic S PHEV'],
  ['Mazda', 'CX-60', 'e-SKYACTIV PHEV Takumi Plus'],
  ['Audi', 'Q3 Sportback Progressive', 'e-hybrid 272 CV S tronic'],
  ['Volvo', 'V60', 'Core T6 AWD Híbrido enchufable'],
  ['Land Rover', 'Range Rover Evoque', 'S PHEV P270e'],
  ['Audi', 'Q3 Sportback S line', 'e-hybrid 272 CV S tronic'],
  ['Audi', 'A5', 'e-hybrid Business quattro 299 CV'],
  ['Volkswagen', 'California', 'Beach Tour 1.5 eHybrid 245 CV DSG 4Motion'],
  ['Hyundai', 'Santa Fe', 'Tecno 1.6 T-GDI PHEV 253 CV 4x4'],
  ['Mazda', 'CX-80', 'Homura 2.5 E-Skyactiv PHEV 327 CV AWD'],
  ['Mercedes-Benz', 'C 300 e', 'Berlina EQ Hybrid'],
  ['Volkswagen', 'Multivan', 'corto Life 1.5 eHybrid 245 CV DSG 4Motion'],
  ['Mazda', 'CX-80', 'Takumi 2.5 E-Skyactiv PHEV 327 CV AWD'],
  ['Lexus', 'NX 450h+', '4x4 Premium+'],
  ['Audi', 'A5 Avant', 'e-hybrid Business quattro 299 CV'],
  ['Mercedes-Benz', 'C 300 e', 'Estate EQ Hybrid'],
  ['BMW', '330e xDrive', 'Touring'],
  ['Audi', 'Q3 Black line', 'e-hybrid 272 CV S tronic'],
  ['Volvo', 'V60', 'Plus T6 AWD Híbrido enchufable'],
  ['Hyundai', 'Santa Fe', 'Style Green 1.6 T-GDI PHEV 253 CV 4x4'],
  ['Hyundai', 'Santa Fe', 'Style 1.6 T-GDI PHEV 253 CV 4x4'],
  ['Audi', 'A5', 'e-hybrid Advanced quattro 299 CV'],
  ['Volvo', 'XC60', 'Core T6 AWD Híbrido enchufable'],
  ['BMW', 'X3', '30e xDrive'],
  ['Mazda', 'CX-80', 'Homura Plus 2.5 E-Skyactiv PHEV 327 CV AWD'],
  ['Audi', 'Q3 Sportback Black line', 'e-hybrid 272 CV S tronic'],
  ['Mercedes-Benz', 'GLC 300 e', '4MATIC EQ Hybrid'],
  ['Land Rover', 'Discovery Sport', 'Landmark PHEV'],
  ['Audi', 'Q5', 'e-hybrid Advanced quattro 299 CV'],
  ['Mazda', 'CX-80', 'Takumi Plus 2.5 E-Skyactiv PHEV 327 CV AWD'],
  ['Hyundai', 'Santa Fe', 'Calligraphy 1.6 T-GDI PHEV 253 CV 4x4'],
  ['Audi', 'A5 Avant', 'e-hybrid Advanced quattro 299 CV'],
  ['Mercedes-Benz', 'GLC 300 de', '4MATIC EQ Hybrid'],
  ['Audi', 'A5', 'e-hybrid S line quattro 299 CV'],
  ['Mercedes-Benz', 'C 300 de', 'Berlina EQ Hybrid'],
  ['Mercedes-Benz', 'E 300 e', 'Berlina EQ Hybrid'],
  ['Lexus', 'NX 450h+', '4x4 Executive+'],
  ['Land Rover', 'Range Rover Evoque', 'Dynamic SE PHEV P270e'],
  ['Mercedes-Benz', 'E 300 de', 'Berlina EQ Hybrid'],
  ['Audi', 'Q5 Sportback', 'e-hybrid Advanced quattro 299 CV'],
  ['Volvo', 'XC60', 'Plus T6 AWD Híbrido enchufable'],
  ['Volvo', 'V60', 'Ultra T6 AWD Híbrido enchufable'],
  ['Mercedes-Benz', 'C 300 de', 'Estate EQ Hybrid'],
  ['Audi', 'A5 Avant', 'e-hybrid S line quattro 299 CV'],
  ['Audi', 'Q5', 'e-hybrid S line quattro 299 CV'],
  ['Mercedes-Benz', 'GLC 300 e', '4MATIC Coupé EQ Hybrid'],
  ['Mercedes-Benz', 'CLE 300 e', 'Coupé EQ Hybrid'],
  ['Mercedes-Benz', 'C 300 de', '4MATIC Berlina EQ Hybrid'],
  ['Mercedes-Benz', 'E 300 e', 'Estate EQ Hybrid'],
  ['Mercedes-Benz', 'GLC 300 de', '4MATIC Coupé EQ Hybrid'],
  ['Volkswagen', 'Multivan', 'corto Style 1.5 eHybrid 245 CV DSG 4Motion'],
  ['Mercedes-Benz', 'E 300 de', '4MATIC Berlina EQ Hybrid'],
  ['Mercedes-Benz', 'E 300 de', 'Estate EQ Hybrid'],
  ['BMW', '530e', 'Berlina'],
  ['Mercedes-Benz', 'C 300 de', '4MATIC Estate EQ Hybrid'],
  ['Audi', 'Q5 Sportback', 'e-hybrid S line quattro 299 CV'],
  ['Volkswagen', 'California', 'Ocean 1.5 eHybrid 245 CV DSG 4Motion'],
  ['Audi', 'A6', 'e-hybrid Advanced quattro 299 CV'],
  ['Mercedes-Benz', 'E 300 de', '4MATIC Estate EQ Hybrid'],
  ['Volkswagen', 'Multivan', 'largo Style 1.5 eHybrid 245 CV DSG 4Motion'],
  ['BMW', '530e xDrive', 'Berlina'],
  ['BMW', '530e', 'Touring'],
  ['Volvo', 'XC60', 'Ultra T6 AWD Híbrido enchufable'],
  ['Audi', 'Q5', 'e-hybrid Black line quattro 299 CV'],
  ['Volvo', 'V90', 'Recharge T6 eAWD Core'],
  ['Jeep', 'Wrangler', '4xe PHEV 381 CV Sahara'],
  ['Audi', 'A6 Avant', 'e-hybrid Advanced quattro 299 CV'],
  ['Land Rover', 'Range Rover Evoque', 'Autobiography PHEV P270e'],
  ['Audi', 'A5', 'e-hybrid Black line quattro 367 CV'],
  ['Audi', 'A6', 'e-hybrid S line quattro 299 CV'],
  ['BMW', '530e xDrive', 'Touring'],
  ['Lexus', 'NX 450h+', '4x4 F Sport'],
  ['Lexus', 'NX 450h+', '4x4 Luxury'],
  ['Audi', 'Q5 Sportback', 'e-hybrid Black line quattro 299 CV'],
  ['Mercedes-Benz', 'E 300 de', '4MATIC All-Terrain EQ Hybrid'],
  ['Jeep', 'Wrangler', '4xe PHEV 381 CV Rubicon'],
  ['Audi', 'A5 Avant', 'e-hybrid Black line quattro 367 CV'],
  ['Audi', 'A6 Avant', 'e-hybrid S line quattro 299 CV'],
  ['Volkswagen', 'Touareg', 'Elegance Final Edition 3.0 V6 TSI eHybrid 381 CV'],
  ['Audi', 'A6', 'e-hybrid Black line quattro 299 CV'],
  ['Volvo', 'V90', 'Recharge T6 eAWD Plus'],
  ['Audi', 'Q5', 'e-hybrid Black competition quattro 367 CV'],
  ['Land Rover', 'Range Rover Velar', 'P400e PHEV S'],
  ['Lexus', 'RX 450h+', 'Business'],
  ['Audi', 'A6 Avant', 'e-hybrid Black line quattro 299 CV'],
  ['Audi', 'Q5 Sportback', 'e-hybrid Black competition quattro 367 CV'],
  ['Volvo', 'V90', 'Recharge T6 eAWD Ultra'],
  ['Land Rover', 'Defender 110', 'S PHEV'],
  ['Volvo', 'XC60', 'Polestar Engineered T8 AWD Híbrido enchufable'],
  ['Jeep', 'Grand Cherokee', '4xe Summit Reserve'],
  ['Audi', 'A6', 'e-hybrid Black line quattro 367 CV'],
  ['Audi', 'Q7', 'Advanced 55 TFSIe quattro'],
  ['BMW', '550e xDrive', 'Berlina'],
  ['Land Rover', 'Range Rover Velar', 'P400e PHEV Dynamic SE'],
  ['Volvo', 'XC90', 'T8 AWD Core'],
  ['Audi', 'A6 Avant', 'e-hybrid Black line quattro 367 CV'],
  ['Volkswagen', 'Touareg', 'R Final Edition 3.0 V6 TSI eHybrid 462 CV'],
  ['BMW', '550e xDrive', 'Touring'],
  ['Lexus', 'RX 450h+', 'Executive+'],
  ['Lexus', 'RX 450h+', 'F Design'],
  ['Volvo', 'XC90', 'T8 AWD Plus'],
  ['Land Rover', 'Defender 110', 'X-Dynamic SE PHEV'],
  ['Mercedes-Benz', 'GLE 400 e', '4MATIC EQ Hybrid'],
  ['Audi', 'Q7', 'S line 55 TFSIe quattro'],
  ['Land Rover', 'Range Rover Velar', 'P400e PHEV Dynamic HSE'],
  ['Mercedes-Benz', 'GLE 350 de', '4MATIC EQ Hybrid'],
  ['Volvo', 'XC90', 'T8 AWD Ultra'],
  ['Lexus', 'RX 450h+', 'Luxury'],
  ['Audi', 'Q8', 'S line 55 TFSIe quattro'],
  ['Land Rover', 'Defender 110', 'X-Dynamic HSE PHEV'],
  ['Land Rover', 'Range Rover Sport', 'S P460e PHEV'],
  ['BMW', 'X5', 'xDrive50e'],
  ['Audi', 'Q7', 'Black line 60 TFSIe quattro'],
  ['Mercedes-Benz', 'GLE 400 e', '4MATIC Coupé EQ Hybrid'],
  ['Audi', 'Q8', 'Black line 60 TFSIe quattro'],
  ['Mercedes-Benz', 'GLE 350 de', '4MATIC Coupé EQ Hybrid'],
  ['Land Rover', 'Range Rover Sport', 'SE P460e PHEV'],
  ['Mercedes-Benz', 'AMG E 53 Hybrid', '4MATIC+ Berlina'],
  ['Mercedes-Benz', 'AMG E 53 Hybrid', '4MATIC+ Estate'],
  ['Mercedes-Benz', 'AMG E 53 Hybrid', '4MATIC+ Berlina AMG Dynamic Plus'],
  ['Porsche', 'Cayenne', 'E-Hybrid'],
  ['Mercedes-Benz', 'AMG E 53 Hybrid', '4MATIC+ Estate AMG Dynamic Plus'],
  ['Mercedes-Benz', 'AMG GLE 53 Hybrid', '4MATIC+'],
  ['Porsche', 'Cayenne', 'E-Hybrid Coupé'],
  ['Land Rover', 'Range Rover Sport', 'Dynamic HSE P460e PHEV'],
  ['Audi', 'A8', '60 TFSIe quattro'],
  ['Audi', 'RS 5', 'PHEV'],
  ['Land Rover', 'Defender 110', 'X PHEV'],
  ['Audi', 'RS 5 Avant', 'PHEV'],
  ['Mercedes-Benz', 'S 450 e', 'EQ Hybrid'],
  ['Audi', 'A8 L', '60 TFSIe quattro'],
  ['Mercedes-Benz', 'AMG GLE 53 Hybrid', '4MATIC+ Coupé'],
  ['Porsche', 'Cayenne S', 'E-Hybrid'],
  ['Mercedes-Benz', 'S 450 e', 'EQ Hybrid Largo'],
  ['BMW', '750e xDrive', 'Berlina'],
  ['BMW', 'XM', '50e'],
  ['Porsche', 'Cayenne S', 'E-Hybrid Coupé'],
  ['Porsche', 'Panamera', '4 E-Hybrid'],
  ['Mercedes-Benz', 'S 580 e', '4MATIC EQ Hybrid'],
  ['Mercedes-Benz', 'S 580 e', '4MATIC EQ Hybrid Largo'],
  ['Mercedes-Benz', 'AMG GLC 63 S', 'E Performance'],
  ['BMW', 'M760e xDrive', 'Berlina'],
  ['Land Rover', 'Range Rover Sport', 'Autobiography P550e PHEV'],
  ['Porsche', 'Panamera', '4 E-Hybrid Executive'],
  ['Mercedes-Benz', 'AMG GLC 63 S', 'E Performance Coupé'],
  ['Land Rover', 'Range Rover', 'P460e PHEV SE Batalla Normal'],
  ['Porsche', 'Panamera', '4S E-Hybrid'],
  ['Mercedes-Benz', 'AMG C 63 S', 'E Performance Berlina'],
  ['Mercedes-Benz', 'AMG C 63 S', 'E Performance Estate'],
  ['Land Rover', 'Range Rover', 'P460e PHEV HSE Batalla Normal'],
  ['Land Rover', 'Range Rover', 'P460e PHEV HSE Batalla Larga'],
  ['BMW', 'M5', 'PHEV'],
  ['BMW', 'M5 Touring', 'PHEV'],
  ['Land Rover', 'Range Rover', 'P550e PHEV HSE Batalla Normal'],
  ['Karma', 'Revero', 'PHEV'],
  ['Land Rover', 'Range Rover', 'P460e PHEV Autobiography Batalla Normal'],
  ['Land Rover', 'Range Rover', 'P460e PHEV Autobiography Batalla Larga'],
  ['Land Rover', 'Range Rover', 'P550e PHEV Autobiography Batalla Normal'],
  ['BMW', 'XM Label', 'PHEV'],
  ['Porsche', 'Cayenne Turbo', 'E-Hybrid'],
  ['Porsche', 'Cayenne Turbo', 'E-Hybrid Coupé'],
  ['Porsche', 'Panamera Turbo', 'E-Hybrid'],
  ['Porsche', 'Cayenne Turbo', 'E-Hybrid Coupé GT'],
  ['Land Rover', 'Range Rover', 'P550e PHEV SV Batalla Normal'],
  ['McLaren', 'Artura', 'Coupé PHEV'],
  ['Mercedes-Benz', 'AMG GT 63 S', 'E Performance Coupé'],
  ['Bentley', 'Bentayga', 'S Hybrid'],
  ['Porsche', 'Panamera Turbo S', 'E-Hybrid'],
  ['Mercedes-Benz', 'AMG GT 63 S', 'E Performance 4 puertas Coupé'],
  ['Porsche', 'Panamera Turbo S', 'E-Hybrid Executive'],
  ['Mercedes-Benz', 'AMG SL 63 S', 'E 4MATIC+ PHEV'],
  ['McLaren', 'Artura', 'Spider PHEV'],
  ['Koenigsegg', 'Gemera', 'PHEV'],
  ['Ford', 'Transit Custom', 'Kombi L1 2.5 PHEV 232 CV Trend'],
  ['Ford', 'Transit Custom', 'Kombi L2 2.5 PHEV 232 CV Trend'],
  ['Ford', 'Transit Custom', 'Kombi L1 2.5 PHEV 232 CV Limited'],
  ['Ford', 'Transit Custom', 'Kombi L2 2.5 PHEV 232 CV Limited'],
  ['Ford', 'Tourneo Custom', 'Titanium 2.5 PHEV 232 CV'],
  ['Ford', 'Grand Tourneo Custom', 'Titanium 2.5 PHEV 232 CV'],
  ['Ford', 'Tourneo Custom', 'Active 2.5 PHEV 232 CV'],
  ['Ford', 'Tourneo Custom', 'Sport 2.5 PHEV 232 CV'],
  ['Ford', 'Grand Tourneo Custom', 'Active 2.5 PHEV 232 CV'],
  ['Ford', 'Tourneo Custom', 'Titanium X 2.5 PHEV 232 CV'],
  ['Ford', 'Grand Tourneo Custom', 'Titanium X 2.5 PHEV 232 CV'],
  ['Volkswagen', 'Caravelle', 'Batalla Corta Premium 2.5 eHybrid 232 CV'],
  ['Volkswagen', 'Caravelle', 'Batalla Larga Premium 2.5 eHybrid 232 CV'],
  ['Ford', 'Ranger', 'Stormtrak Doble Cabina 2.3 PHEV 280 CV'],
  ['Ford', 'Ranger', 'MS-RT Doble Cabina 2.3 PHEV 280 CV'],
  ['Ford', 'Ranger', 'Wildtrak Doble Cabina 2.3 PHEV 280 CV (v2)'],
  ['Volkswagen', 'California', 'Beach Tour eHybrid'],
  ['Volkswagen', 'California', 'Ocean eHybrid'],
  ['Mercedes-Benz', 'AMG GT 4 Puertas', '63 S E Performance'],
  ['Tesla', 'Model 3', 'Standard Range AWD'],
  ['Tesla', 'Model 3', 'Long Range AWD'],
  ['Tesla', 'Model 3', 'Performance AWD'],
  ['Tesla', 'Model Y', 'Standard Range RWD'],
  ['Tesla', 'Model Y', 'Long Range AWD'],
  ['Tesla', 'Model Y', 'Performance AWD'],
  ['Tesla', 'Model S', 'Standard Range'],
  ['Tesla', 'Model S', 'Plaid'],
  ['Tesla', 'Model X', 'Long Range AWD'],
  ['Tesla', 'Model X', 'Plaid'],
  ['Kia', 'EV3', 'Standard Range 58 kWh'],
  ['Kia', 'EV3', 'Long Range 81 kWh'],
  ['Kia', 'EV6', 'Standard Range RWD'],
  ['Kia', 'EV6', 'Long Range RWD'],
  ['Kia', 'EV6', 'Long Range AWD'],
  ['Kia', 'EV6', 'GT'],
  ['Kia', 'EV9', 'Long Range RWD 6 plazas'],
  ['Kia', 'EV9', 'Long Range AWD 7 plazas'],
  ['Kia', 'EV4', 'Air 81 kWh 204 CV'],
  ['Kia', 'Niro EV', 'Long Range 64.8 kWh'],
  ['Renault', '5 E-Tech', '120 CV Standard Range'],
  ['Renault', '5 E-Tech', '150 CV Long Range'],
  ['Renault', 'Zoe', 'R110 52 kWh'],
  ['Renault', 'Megane E-Tech', 'EV40 130 CV'],
  ['Renault', 'Megane E-Tech', 'EV60 220 CV'],
  ['Renault', 'Scenic E-Tech', 'Autonomía Estándar 170 CV'],
  ['Renault', 'Scenic E-Tech', 'Gran Autonomía 220 CV'],
  ['BYD', 'Dolphin Surf', 'Standard 45 kWh'],
  ['BYD', 'Dolphin Surf', 'Long Range 60 kWh'],
  ['BYD', 'Dolphin', 'Standard Range 44 kWh'],
  ['BYD', 'Dolphin', 'Long Range 60 kWh'],
  ['BYD', 'Atto 3', 'Standard Range 60 kWh'],
  ['BYD', 'Atto 3', 'Long Range 82 kWh'],
  ['BYD', 'Han', 'EV AWD 85 kWh'],
  ['BYD', 'Tang', 'EV 4WD 108 kWh'],
  ['BYD', 'Seal', 'RWD 82 kWh'],
  ['BYD', 'Seal', 'AWD 82 kWh'],
  ['BYD', 'Sealion 6', 'AWD'],
  ['Toyota', 'bZ4X', 'FWD 71,4 kWh'],
  ['Toyota', 'bZ4X', 'AWD 72,8 kWh'],
  ['Volkswagen', 'ID.3', 'Pro 58 kWh'],
  ['Volkswagen', 'ID.3', 'Pro S 77 kWh'],
  ['Volkswagen', 'ID.4', 'Pro 77 kWh'],
  ['Volkswagen', 'ID.4', 'GTX 77 kWh'],
  ['Volkswagen', 'ID.5', 'Pro 77 kWh'],
  ['Volkswagen', 'ID.5', 'GTX 77 kWh'],
  ['Volkswagen', 'ID.7', 'Pro 77 kWh'],
  ['Volkswagen', 'ID.7', 'Pro S 91 kWh'],
  ['Audi', 'Q4 e-tron', '35 52 kWh RWD'],
  ['Audi', 'Q4 e-tron', '40 82 kWh RWD'],
  ['Audi', 'Q4 e-tron', '45 82 kWh quattro'],
  ['Audi', 'Q4 Sportback e-tron', '40 82 kWh RWD'],
  ['Audi', 'Q6 e-tron', 'RWD 100 kWh'],
  ['Audi', 'Q6 e-tron', 'quattro 100 kWh SQ6'],
  ['Audi', 'e-tron GT', 'quattro 93 kWh'],
  ['Audi', 'RS e-tron GT', 'Performance 105 kWh'],
  ['BMW', 'iX3', '50 xDrive 108,7 kWh'],
  ['BMW', 'i4', 'eDrive40 83,9 kWh'],
  ['BMW', 'i4', 'M50 83,9 kWh'],
  ['BMW', 'iX', 'xDrive40 76,6 kWh'],
  ['BMW', 'iX', 'xDrive50 111,5 kWh'],
  ['BMW', 'i5', 'eDrive40 84 kWh'],
  ['BMW', 'i5', 'M60 xDrive 84 kWh'],
  ['BMW', 'i7', 'xDrive60 105,7 kWh'],
  ['Mercedes-Benz', 'EQA', '250 66,5 kWh'],
  ['Mercedes-Benz', 'EQA', '300 4MATIC 66,5 kWh'],
  ['Mercedes-Benz', 'EQB', '300 4MATIC 66,5 kWh'],
  ['Mercedes-Benz', 'EQE', '300 90,6 kWh'],
  ['Mercedes-Benz', 'EQE', '500 4MATIC 90,6 kWh'],
  ['Mercedes-Benz', 'EQS', '450+ 107,8 kWh'],
  ['Mercedes-Benz', 'EQS', '500 4MATIC 118 kWh'],
  ['Mercedes-Benz', 'CLA', '250+ 85 kWh'],
  ['Mercedes-Benz', 'CLA', '350 4MATIC 85 kWh'],
  ['Hyundai', 'Ioniq 5', 'Standard Range 58 kWh'],
  ['Hyundai', 'Ioniq 5', 'Long Range RWD 77,4 kWh'],
  ['Hyundai', 'Ioniq 5', 'Long Range AWD 77,4 kWh'],
  ['Hyundai', 'Ioniq 6', 'Standard Range RWD 53 kWh'],
  ['Hyundai', 'Ioniq 6', 'Long Range RWD 77,4 kWh'],
  ['Hyundai', 'Ioniq 6', 'Long Range AWD 77,4 kWh'],
  ['Hyundai', 'Kona EV', 'Standard 48,4 kWh'],
  ['Hyundai', 'Kona EV', 'Long Range 65,4 kWh'],
  ['Peugeot', 'e-208', 'Standard 51 kWh'],
  ['Peugeot', 'e-208', 'Long Range 54 kWh'],
  ['Peugeot', 'e-2008', 'Standard 54 kWh'],
  ['Peugeot', 'e-2008', 'Long Range 54 kWh'],
  ['Citroën', 'ë-C3', '50 kWh'],
  ['Citroën', 'ë-C4', '54 kWh'],
  ['Opel', 'Corsa Electric', '54 kWh'],
  ['Opel', 'Mokka Electric', '54 kWh'],
  ['Opel', 'Astra Electric', '54 kWh'],
  ['Skoda', 'Enyaq', '60 62 kWh'],
  ['Skoda', 'Enyaq', '85 82 kWh'],
  ['Skoda', 'Enyaq', '85x 82 kWh AWD'],
  ['SEAT', 'el-Born', '58 kWh'],
  ['CUPRA', 'Born', '58 kWh 231 CV'],
  ['CUPRA', 'Born', '77 kWh 286 CV'],
  ['CUPRA', 'Tavascan', '77 kWh RWD'],
  ['CUPRA', 'Tavascan', '77 kWh AWD 340 CV'],
  ['Volvo', 'EX30', 'Single Motor Extended Range 69 kWh'],
  ['Volvo', 'EX30', 'Twin Motor Performance'],
  ['Volvo', 'EX40', 'Single Motor Extended Range'],
  ['Volvo', 'EX40', 'Twin Motor'],
  ['Volvo', 'EC40', 'Single Motor Extended Range'],
  ['Volvo', 'EX90', 'Twin Motor 111 kWh'],
  ['Polestar', '2', 'Standard Range Single Motor'],
  ['Polestar', '2', 'Long Range Single Motor'],
  ['Polestar', '2', 'Long Range Dual Motor'],
  ['Polestar', '3', 'Long Range Single Motor'],
  ['Polestar', '3', 'Long Range Dual Motor 107 kWh'],
  ['Ford', 'Mustang Mach-E', 'Standard Range RWD 75 kWh'],
  ['Ford', 'Mustang Mach-E', 'Extended Range RWD 91 kWh'],
  ['Ford', 'Mustang Mach-E', 'Extended Range AWD 91 kWh'],
  ['Ford', 'Explorer', 'Standard Range RWD 77 kWh'],
  ['Ford', 'Capri', 'Select Rango Extendido RWD 77 kWh'],
  ['Nissan', 'Leaf', '40 kWh'],
  ['Nissan', 'Leaf', '62 kWh'],
  ['Nissan', 'Ariya', '63 kWh FWD'],
  ['Nissan', 'Ariya', '87 kWh FWD'],
  ['Fiat', '500e', 'Action 23,8 kWh'],
  ['Fiat', '500e', 'Icon 42 kWh'],
  ['Fiat', '500e', 'La Prima 42 kWh Cabrio'],
  ['MINI', 'Electric', 'Hatchback 40,7 kWh'],
  ['MINI', 'Countryman', 'E 64,7 kWh'],
  ['MINI', 'Aceman', 'E 54,2 kWh'],
  ['Alfa Romeo', 'Junior', 'Electric 54 kWh'],
  ['Jeep', 'Avenger', 'Electric 54 kWh'],
  ['Mazda', 'MX-30', 'e-SKYACTIV 35,5 kWh'],
  ['Honda', 'e:Ny1', '68,8 kWh'],
  ['MG', 'MG4', 'Standard 51 kWh'],
  ['MG', 'MG4', 'Long Range 77 kWh'],
  ['MG', 'MG4', 'XPOWER AWD 77 kWh'],
  ['MG', 'Marvel R', 'Electric AWD 70 kWh'],
  ['MG', 'ZS EV', 'Standard 51,1 kWh'],
  ['MG', 'ZS EV', 'Long Range 72,6 kWh'],
  ['Omoda', 'E5', '61 kWh'],
  ['Jaecoo', 'J7 EV', '70,3 kWh'],
  ['Leapmotor', 'T03', '37,3 kWh'],
  ['Leapmotor', 'C10', 'BEV 69,9 kWh'],
  ['Lexus', 'RZ 450e', '71,4 kWh AWD'],
  ['Lexus', 'UX 300e', '72,8 kWh'],
  ['Subaru', 'Solterra', '71,4 kWh AWD'],
  ['Mitsubishi', 'Eclipse Cross', 'EV 70 kWh'],
  ['smart', '#1', 'Pulse 66 kWh'],
  ['smart', '#3', 'Brabus AWD 66 kWh']
];

$stmt = $db->prepare('INSERT IGNORE INTO custom_vehicles (make, model, version) VALUES (?, ?, ?)');
$inserted = 0;
foreach ($vehicles as $v) {
    $stmt->execute($v);
    $inserted += $stmt->rowCount();
}

json(['ok' => true, 'inserted' => $inserted, 'total' => count($vehicles)]);
